/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '100041' at '23/8/16 11:53 AM' with Gradle 2.10
 *
 * @author 100041, @date 23/8/16 11:53 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
